version: '2'

services:
  this_jup:
    build: docker/jupyter
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan

  this_postgres:
    build: docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
