version: '2'

services:
  this_jup:
    image: jupyter/scipy-notebook
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan

  this_mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
